---
application:
  name: "telegram-twitter-forwarder-bot"
  project: "twitterbot"
  organization: "QoveryCommunity"
routers:
- name: "main-telegram-twitter-forwarder-bot"
  routes:
  - application_name: "telegram-twitter-forwarder-bot"
    paths:
    - "/*"
